# site.yml
---

- hosts: srv002
  roles:
  - ansible-role-oracle-java-master
  - ansible-role-hadoop-master
  - ansible-role-apache-spark-master
  vars: 
    - hadoop_type_of_node: master
    - hadoop_master: srv002
